const ADD_TASK = 'ADD_TASK'
const ADD_GROUP = 'ADD_GROUP'
const COMPLETE = 'COMPLETE'
const TASK_MODAL = 'TASK_MODAL'
const GROUP_MODAL = 'GROUP_MODAL'
const SET_SELECTED = 'GROUP_MODAL'

export {
    ADD_TASK,
    ADD_GROUP,
    COMPLETE,
    TASK_MODAL,
    GROUP_MODAL,
    SET_SELECTED,
}